### ISSUE TITLE
why not make trivially_copyable_tuple trivially constructible

### ISSUE THREAD

**Issue by scinart** [geneotech/Mechanical-keyboard-simulator#1]
since `std::tuple` is trivially constructible

		static_assert(are_types_memcpy_safe_v<Types...>, "One of the tuple types is not trivially copyable!");
		trivially_copyable_tuple() noexcept {std::memset(this, sizeof(*this), 0);}
		trivially_copyable_tuple(const trivially_copyable_tuple& rhs) noexcept = default;
		trivially_copyable_tuple(trivially_copyable_tuple&&) noexcept = default;
		trivially_copyable_tuple& operator=(const trivially_copyable_tuple&) noexcept = default;
		trivially_copyable_tuple(Types... args) noexcept {
			// zero-initialize the memory so that delta encoding does not see the padding bytes as different
			std::memset(this, sizeof(*this), 0);
			new (buf) tuple_type(Types(args)...);
		}

**Comment by geneotech** [comment]
This issue probably belongs to:
https://github.com/TeamHypersomnia/Hypersomnia/issues 
...since this is where the most recent version of this source resides. Hope you enjoyed the simulator! :grin:   

Currently my default constructor looks like this:

```cpp
		template <class type>
		void init() {
			static constexpr std::size_t offset = sum_sizes_until_nth_v<index_in_v<type, Types...>, type_list<Types...>>;
			
			auto* const p = data() + offset;

			new (p) type;
		}

	public:

		static_assert(std::conjunction_v<std::is_trivially_copyable<Types>...>, "One of the tuple types is not trivially copyable!");

		trivially_copyable_tuple() {
			(init<Types>(), ...);
		}

		char* data() {
			return reinterpret_cast<char*>(&buf);
		}
```

I could probably make a specialization of the trivially_copyable_tuple so that it does not define a constructor when all the types are trivially constructible, but I only really care about memcpy-safety, which is already ensured by being trivially copyable.

Unfortunately, std::tuple of trivial types is not necessarily trivially_copyable, as seen here:
https://stackoverflow.com/questions/38779985/why-cant-stdtupleint-be-trivially-copyable
And I need such a tuple due to some traits I take advantage of, hence the need for such a class.

**Comment by scinart** [comment]
I noticed that lots of code has been changed in https://github.com/TeamHypersomnia/Hypersomnia/blob/master/src/augs/misc/trivially_copyable_tuple.h

This issue should be closed...
